pipeline {
	agent { label 'slave2' }
  tools {
    maven 'maven-3.9.2' 
  }
  stages {
    stage ('Build') {
      steps {
        sh '''
        	cd ./maven/sparkjava-war 
        	mvn clean package
        	cd ./maven/sparkjava-war/target/
        	ls
           '''
      }
    }
    stage ('Deploy') {
      steps {
        script {
          deploy adapters: [tomcat9(credentialsId: 'tomcat_manager', path: '', url: 'http://65.2.40.144:8080/')], contextPath: '/javaWebApp', onFailure: false, war: 'maven/sparkjava-war/target/*.war' 
        }
      }
    }
  }
}