pipeline {
	agent any
  tools {
    maven 'maven-3.9.2' 
  }
  stages {
    stage ('Build') {
      steps {
        sh 'pwd; ls; mvn clean package'
      }
    }
    stage ('Deploy') {
      steps {
        script {
          deploy adapters: [tomcat9(credentialsId: 'tomcat_manager', path: '', url: 'http://65.2.40.144:8080/')], contextPath: '/pipeline', onFailure: false, war: 'webapp/target/*.war' 
        }
      }
    }
  }
}