pipeline {
    agent {
        label 'slave1'
    }
 
    stages {
       stage ('BUILD') {
           steps {
                sh 'sleep 5'
           }
       } 
       
       stage ('TEST') {
           steps {
                sh 'exit 1'
           }
       }
        
       stage ('DEPLOY') {
           steps {
                sh 'sleep 5'
           }
       }  
       stage ('DEPLOY1') {
           steps {
                sh 'sleep 5'
           }
       }     
    }
}
